### ISSUE TITLE
Problems running dataconvert -h

### ISSUE THREAD

**Issue by mtarinalfatec** [okfn/dataconverters#105]
Hello 
I just installed from source dataconvert in Red Hat Enterprise Linux Server release 7.3 = 

.... Clone the repository
https://github.com/okfn/dataconverters
 
....then install the lib ...

....move into the directory
cd dataconverters

... install the library
pip install -e .
.. .you can use the more old-fashioned route if you do not have pip
... python setup.py install

Not having obtained any installation error. With the last installation command result = 

[root@localhost dataconverters-master]# python setup.py install
running install
running bdist_egg
running egg_info
writing dataconverters.egg-info/PKG-INFO
writing top-level names to dataconverters.egg-info/top_level.txt
writing dependency_links to dataconverters.egg-info/dependency_links.txt
writing entry points to dataconverters.egg-info/entry_points.txt
reading manifest file 'dataconverters.egg-info/SOURCES.txt'
writing manifest file 'dataconverters.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dataconverters
copying dataconverters/arff.py -> build/lib/dataconverters
copying dataconverters/cli.py -> build/lib/dataconverters
copying dataconverters/commas.py -> build/lib/dataconverters
copying dataconverters/jsondata.py -> build/lib/dataconverters
copying dataconverters/kml.py -> build/lib/dataconverters
copying dataconverters/shp.py -> build/lib/dataconverters
copying dataconverters/xls.py -> build/lib/dataconverters
copying dataconverters/__init__.py -> build/lib/dataconverters
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/arff.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/cli.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/commas.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/jsondata.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/kml.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/shp.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/xls.py -> build/bdist.linux-x86_64/egg/dataconverters
copying build/lib/dataconverters/__init__.py -> build/bdist.linux-x86_64/egg/dataconverters
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/arff.py to arff.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/commas.py to commas.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/jsondata.py to jsondata.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/kml.py to kml.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/shp.py to shp.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/xls.py to xls.pyc
byte-compiling build/bdist.linux-x86_64/egg/dataconverters/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dataconverters.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dataconverters.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dataconverters.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dataconverters.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dataconverters.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dataconverters-0.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dataconverters-0.4-py2.7.egg
Copying dataconverters-0.4-py2.7.egg to /usr/lib/python2.7/site-packages
Removing dataconverters 0.4 from easy-install.pth file
Adding dataconverters 0.4 to easy-install.pth file
Installing dataconvert script to /usr/bin

Installed /usr/lib/python2.7/site-packages/dataconverters-0.4-py2.7.egg
Processing dependencies for dataconverters==0.4
Finished processing dependencies for dataconverters==0.4

And when I execute a simply “dataconvert –h”. I obtain this error= 

[root@localhost CONVERTIDOR]# cd /usr/bin
[root@localhost bin]# dataconvert -h
Traceback (most recent call last):
  File "/usr/bin/dataconvert", line 9, in <module>
    load_entry_point('dataconverters==0.4', 'console_scripts', 'dataconvert')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/dataconverters/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/dataconverters/commas.py", line 3, in <module>
ImportError: No module named unicodecsv

It seems dataconvert is not running. ¿ Can you help me ? 

Thanks in advance

**Comment by rgrp** [comment]
did you install the library with pip install or ...

Checking the code it looks like the dependencies may not be installed if you don't install with pip ... (which is something of a bug in itself ...)

**Comment by mtarinalfatec** [comment]
hello 

I justo followed your instructions (pip used). 

For solving the issue I had to ejecute after

pip install unicodecsv
pip install messytables

then dataconvert running !

thanks

**Comment by rufuspollock** [comment]
FIXED.
